force-app/main/default/objects/Compte_rendu_activit__c/Compte_rendu_activit__c.object-meta.xml
<CustomObject>
    <label>Compte rendu activité</label>
    <nameField>
        <label>Compte rendu activité Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes rendu activité</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compte_rendu_activit__c/fields/Sum_values__c.field-meta.xml
<CustomField>
    <fullName>Sum_values__c</fullName>
    <label>Nombre de jours travaillés</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CompteRenduActiviteController.cls
public with sharing class CompteRenduActiviteController {
    @AuraEnabled
    public static void saveSum(Decimal sumValue) {
        // Charger l'enregistrement du Compte_rendu_activit__c lié
        //Compte_rendu_activit__c compteRendu = [SELECT Id, Sum_values__c FROM Compte_rendu_activit__c LIMIT 1]; 
        Compte_rendu_activit__c compteRendu = new Compte_rendu_activit__c();
        compteRendu.Sum_values__c = sumValue;
        
        // Sauvegarder les modifications
        insert compteRendu;
    }
}